// This file will be generated by Supabase CLI
// Run: npm run generate-types

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          household_id: string | null
          privacy_mode: boolean
          local_mode: boolean
          timezone: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          household_id?: string | null
          privacy_mode?: boolean
          local_mode?: boolean
          timezone?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          household_id?: string | null
          privacy_mode?: boolean
          local_mode?: boolean
          timezone?: string
          created_at?: string
          updated_at?: string
        }
      }
      // Additional tables will be generated here
    }
    Views: {
      // Views will be generated here
    }
    Functions: {
      // Functions will be generated here
    }
    Enums: {
      // Enums will be generated here
    }
  }
}

export type Tables<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Row']
export type Inserts<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Insert']
export type Updates<T extends keyof Database['public']['Tables']> = Database['public']['Tables'][T]['Update']